package com.github.copilot.demo.model;

/**
 * Student model class
 * 
 * Copilot Usage Examples:
 * 1. Type: "// Student class with id, name, email, major" and Copilot suggests the fields
 * 2. Type: "// constructor" and Copilot generates constructors
 * 3. Type: "// getters and setters" and Copilot generates all accessor methods
 * 4. After creating fields, type "public Student(" and Copilot suggests constructor with all fields
 */
public class Student {
    private Long id;
    private String name;
    private String email;
    private String major;

    // Default constructor
    public Student() {
    }

    // Constructor with all fields - Generated with Copilot
    public Student(Long id, String name, String email, String major) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.major = major;
    }

    // Getters and Setters - Can be generated by Copilot
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMajor() {
        return major;
    }

    public void setMajor(String major) {
        this.major = major;
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", major='" + major + '\'' +
                '}';
    }
}
